### PR TITLE
Implementing a Terminal Mode that lets you use BlenderVR in the console

### PR DESCRIPTION
**Pull request by perezsaint**
With this you can use blendervr from a linux console. All the changes and options are in the README_TERMINAL.txt file.

### CODE REVIEW

**Comment by dfelinto** [comment]
Does this patch also remove QT as a requirement for the BlenderVR installation?

**Comment by perezsaint** [comment]
Yeah, Qt isn't necessary to run simulations in the terminal mode.

**Comment by perezsaint** [comment]
It is still necessary (obviously) to use BlenderVR with the GUI

**Comment by perezsaint** [comment]
There's a problem however trying to run this from the Windows CMD.  When the daemons start blenderplayer, blenderplayer forces the CMD console to close stopping the simulation. I guess this is a blender problem. Because of this, this only works in Linux.

**Comment by wphicks** [comment]
Is the Windows issue the primary thing that is keeping this PR from being merged, or are there other changes needed? I'd love to see this pulled in, so if there's anything I can do to help with cleanup/review, I'd be happy to contribute.

**Comment by PyrApple** [comment]
The only thing delaying the PR is time for review + test on CAVE / HMD architectures. If one acknowledges that the command line version works on both (while I see no reason why it shouldn't) we'd be glad to go for the merge.

**Comment by wphicks** [comment]
Okay, great! I'll be visiting the Brown University CAVE later this week, and I'll try to do some testing and post feedback then. Thanks very much.

**Comment by perezsaint** [comment]
Hey,

I can attest that it is currently working in Brown's YURT. When you go
there, there's a section in the demos screen that has some of the blender
sample apps.

 I also fixed the problem with the synchronization of newly created
objects. there's a demo called nerf gun where you can shoot nerf guns with
a wand that shows this working.


2016-09-26 12:49 GMT-04:00 William Hicks <notifications@github.com>:

**Comment by wphicks** [comment]
Great! Just to make sure I understand, do you mean that this pull request contains the fix for the new object synchronization issue, or is there another commit I should check out for that fix?

**Comment by perezsaint** [comment]
It's not in this commit. I haven't pushed the other commit with the
synchronization fix. When I have time I'll do a pull request.

2016-09-26 15:31 GMT-04:00 William Hicks <notifications@github.com>:

**Comment by wphicks** [comment]
Ah, gotcha. Going to take this conversation to issue #43, since it's not directly related to this PR.

**Comment by bfgkatz** [comment]
Hi,
We would love to add a short description of your demos or installation examples of BlenderVR on the Web site. These could be a short description with a photo or two and a link to your site. Please also feel free to keep us informed of any publications that you have using BlenderVR.
Thanks in advance, -The BlenderVR team



-------- Original message --------

**Comment by PyrApple** [comment]
Perezsaint, let me know if you're interested in being added to BlenderVR github devs. Our thanks for the contribution.

**Pull request merged**
